MAKE=make

info:
	@echo " "
	@echo " Possible targets are: "
	@echo "     all           perform all the calculation steps"
	@echo "     want          perform only the WanT calculations"
	@echo "     clean         clean up"
	@echo " "

all: 
	./run_Au.sh all
	./run_AuUS.sh all

want: 
	./run_Au.sh want
	./run_AuUS.sh want

clean:
	./run_Au.sh clean
	./run_AuUS.sh clean

