#
#===============================
# WanT package
#===============================
#
include ../make.sys


#
# MAIN target
#
all: vdW-WF


#
# vdW-WF
#
vdW-WF:
	 if test -d vdw-wf ;    then ( cd vdw-wf;    $(MAKE) ) ; fi

#
# cleaning
#
clean clean_all:
	 if test -d vdw-wf ;    then ( cd vdw-wf;    $(MAKE) $@ ) ; fi

