MAKE=make

info:
	@echo " "
	@echo " Possible targets are: "
	@echo "     all           perform all the calculation steps"
	@echo "     want          perform only the WanT calculations"
	@echo "     clean         clean up"
	@echo " "

all: 
	./run.sh all
	./run_US.sh all

want: 
	./run.sh want
	./run_US.sh want

clean:
	./run.sh clean
	./run_US.sh clean
