MAKE=make

info:
	@echo " "
	@echo " Possible targets are: "
	@echo "     all           perform all the calculation steps"
	@echo "     want          perform only the WanT calculations"
	@echo "     clean         clean up"
	@echo " "

all: 
	./run_Cu.sh all
	./run_CuUS.sh all
	./run_CoUS.sh all

want: 
	./run_Cu.sh want
	./run_CuUS.sh want
	./run_CoUS.sh want

clean:
	./run_Cu.sh clean
	./run_CuUS.sh clean
	./run_CoUS.sh clean

