MAKE=make

info:
	@echo " "
	@echo " Possible targets are: "
	@echo "     run           perform all the calculation steps"
	@echo "     want          perform only the WanT calculations"
	@echo "     clean         clean up"
	@echo " "

run: 
	./run.sh all

want: 
	./run.sh want

clean:
	./run.sh clean
